### ISSUE TITLE
FileSettings.encodeToData() is returning to few data 

### ISSUE THREAD

**Issue by MichaelsPlayground** [johnnyb/ntag424-java#5]
Running FileSettings.encodeToData() is giving to few data, e.g.

`File 01: length: 3 data: 0000e0`

Using this output as input for FileSettings.decodeFromData(xx) gives an **ArrayIndexOutOfBoundsException**:

```
FATAL EXCEPTION: Thread-7
Process: de.androidcrypto.ntag424testapp, PID: 24668
java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
	at net.bplearning.ntag424.command.FileSettings.decodeFromData(FileSettings.java:46)
	at de.androidcrypto.ntag424testapp.MainActivity$28.run(MainActivity.java:4787)
	at java.lang.Thread.run(Thread.java:764)
```

NTAG 424 DNA NT4H2421Gx.pdf page 69 ff is stating a minimum of 7 bytes + extra bytes if SDM is enabled.

Greetings
Michael (AndroidCrypto)

**Comment by MichaelsPlayground** [comment]
The _encodeToData_ returns this 3 byte (hex) byte sequence for file 01: 0000e0

As per NTAG424 datasheet the "GetFileSettings" command should return a minimum of 7 bytes + extra bytes if SDM is enabled:

<img width="444" alt="NTAG424_GetFileSettingsResponse" src="https://github.com/johnnyb/ntag424-java/assets/92245023/ae5315f7-0f2f-4c2e-bc1b-64219b35294a">

If I'm using the (hex) byte sequence "0000e012200000" as input for _decodeFromData_ I can build a new FileSettings object. I didn't test for decoding data including SDM options.
